_wandb:
    value:
        cli_version: 0.18.5
        m: []
        python_version: 3.10.15
        t:
            "1":
                - 1
                - 2
                - 3
                - 5
                - 11
                - 41
                - 49
                - 53
                - 55
                - 63
                - 71
                - 98
                - 105
            "2":
                - 1
                - 2
                - 3
                - 5
                - 11
                - 41
                - 49
                - 53
                - 55
                - 63
                - 71
                - 98
                - 105
            "3":
                - 13
                - 23
                - 55
            "4": 3.10.15
            "5": 0.18.5
            "6": 4.33.1
            "8":
                - 5
            "12": 0.18.5
            "13": linux-x86_64
